version: "2.3"
services:
  database:
    image: postgres:11.4-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "3000:3000"
  expire-payment-code-cron:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 9092:9092
    env_file:
      - .env
    command: /app/engine expire-payment-code
volumes:
  data: