// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xtianatilano/christian-golang-training-beginner/inquiries (interfaces: PaymentCodeService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	golangtraining "github.com/xtianatilano/christian-golang-training-beginner"
)

// MockPaymentCodeService is a mock of PaymentCodeService interface.
type MockPaymentCodeService struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentCodeServiceMockRecorder
}

// MockPaymentCodeServiceMockRecorder is the mock recorder for MockPaymentCodeService.
type MockPaymentCodeServiceMockRecorder struct {
	mock *MockPaymentCodeService
}

// NewMockPaymentCodeService creates a new mock instance.
func NewMockPaymentCodeService(ctrl *gomock.Controller) *MockPaymentCodeService {
	mock := &MockPaymentCodeService{ctrl: ctrl}
	mock.recorder = &MockPaymentCodeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentCodeService) EXPECT() *MockPaymentCodeServiceMockRecorder {
	return m.recorder
}

// GetByPaymentCode mocks base method.
func (m *MockPaymentCodeService) GetByPaymentCode(arg0 string) (golangtraining.PaymentCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPaymentCode", arg0)
	ret0, _ := ret[0].(golangtraining.PaymentCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPaymentCode indicates an expected call of GetByPaymentCode.
func (mr *MockPaymentCodeServiceMockRecorder) GetByPaymentCode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPaymentCode", reflect.TypeOf((*MockPaymentCodeService)(nil).GetByPaymentCode), arg0)
}
